import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/navbar";

export const metadata: Metadata = {
  title: "Gift Click",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt">
      <body className="w-screen min-h-screen max-h-screen bg-white flex-col flex px-[6vw]">
        <Navbar/>
        <div className="w-full h-fit">
          {children}
        </div>
        
      </body>
    </html>
  );
}
