import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/navbar";
import Footer from "./components/footer";

export const metadata: Metadata = {
  title: "Gift Click",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt">
      <body className="w-screen min-h-screen max-h-screen bg-white flex-col flex">
        <Navbar/>
        <div className="w-full h-fit overflow-y-scroll px-[6vw]">
          <div className="h-[1000px]">
            {children}
          </div>
          <Footer/>
        </div>
      </body>
    </html>
  );
}
